INSERT INTO bank.account (account_id,customer_id,account_balance,account_name,account_type,created_datetime,last_updated)
       VALUES (now(),now(),1001,'acc_001','Checking',toTimeStamp(now()),toTimeStamp(now()));
INSERT INTO bank.account (account_id,customer_id,account_balance,account_name,account_type,created_datetime,last_updated)
       VALUES (now(),now(),1002,'acc_002','Checking',toTimeStamp(now()),toTimeStamp(now()));
INSERT INTO bank.account (account_id,customer_id,account_balance,account_name,account_type,created_datetime,last_updated)
       VALUES (now(),now(),1003,'acc_003','Savings',toTimeStamp(now()),toTimeStamp(now()));
INSERT INTO bank.account (account_id,customer_id,account_balance,account_name,account_type,created_datetime,last_updated)
       VALUES (now(),now(),1004,'acc_004','Checking',toTimeStamp(now()),toTimeStamp(now()));
